version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: example_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_sea_query
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_example_sea_query
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d example_sea_query"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    image: ghcr.io/mamangrust/example_sea_query:latest
    container_name: example_sea_query_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_example_sea_query
    ports:
      - "8000:8000"

volumes:
  postgres_data:

networks:
  app_example_sea_query:
    driver: bridge
